const Database = [
    {
     id: 270,
      category: "Computer",
      brand: "Asus",
      need: "Video",
      price: 1591,
      energyClass: "D",
      ges: "E",
      batteryMovable: false,
      batteryRecyclability: 90,
      screenSize: 13,
      shutDownAuto: false,
      autonomy: 54,
      description: "Jamais aucun autre ordinateur portable n'avait offert autant de puissance que le ZenBook Pro 15. Ses performances sont plus rapides, son design plus élégant et son nouveau ScreenPad™ décuple votre créativité ! Avec le ZenBook Pro vous faites un saut dans le temps : le futur est ici et maintenant ! ",
      image: "http://i2.cdscdn.com/pdt2/3/v/1/4/300x300/occ9agn4j2293v1/rw/asus-rog-pc-gamer-g502vs-fy091d-15-6-8go-de-ram.jpg",
      model: "ASUS TUF504GD-DM915T",
      ecologyNotice: "Moyen moins"
    },
    {
      id: 271,
      category: "Computer",
      brand: "Asus",
      need: "Office",
      price: 1103,
      energyClass: "C",
      ges: "C",
      batteryMovable: false,
      batteryRecyclability: 47,
      screenSize: 11,
      shutDownAuto: false,
      autonomy: 19,
      description: "Jamais aucun autre ordinateur portable n'avait offert autant de puissance que le ZenBook Pro 15. Ses performances sont plus rapides, son design plus élégant et son nouveau ScreenPad™ décuple votre créativité ! Avec le ZenBook Pro vous faites un saut dans le temps : le futur est ici et maintenant ! ",
      image: "https://i2.cdscdn.com/pdt2/2/8/8/1/300x300/asus501uaej1288/rw/ordinateur-portable-asus-s501ua-ej1288t-15-fhd.jpg",
      model: "ASUS R540LA-XX1034T",
      ecologyNotice: "Moyen plus"
    },
    {
      id: 272,
      category: "Computer",
      brand: "Asus",
      need: "Gaming",
      price: 1356,
      energyClass: "C",
      ges: "C",
      batteryMovable: true,
      batteryRecyclability: 85,
      screenSize: 11,
      shutDownAuto: false,
      autonomy: 74,
      description: "Jamais aucun autre ordinateur portable n'avait offert autant de puissance que le ZenBook Pro 15. Ses performances sont plus rapides, son design plus élégant et son nouveau ScreenPad™ décuple votre créativité ! Avec le ZenBook Pro vous faites un saut dans le temps : le futur est ici et maintenant ! ",
      image: "https://dyw7ncnq1en5l.cloudfront.net/optim/produits/150/49481/asus-vivobook-s14-s430ua_f02a8a2ef7a4fdb6__300_300.jpg",
      model: "ASUS S430UA-EB265T",
      ecologyNotice: "Moyen plus"
    },
    {
      id: 273,
      category: "Computer",
      brand: "Lenovo",
      need: "Office",
      price: 1098,
      energyClass: "B",
      ges: "B",
      batteryMovable: false,
      batteryRecyclability: 69,
      screenSize: 16,
      shutDownAuto: false,
      autonomy: 79,
      description: "Legion 730 15\" Combinant puissance et portabilité dans un design repensé à couper le souffle,il fait passer le jeu sur portable au niveau supérieur",
      image: "http://www.annuaires-francophonie.com/wp-content/uploads/2018/10/lenovo-ideapad-320-15ast.jpg",
      model: "LENOVO IDEAPAD 320-15AST",
      ecologyNotice: "Bien"
    },
    {
      id: 274,
      category: "Computer",
      brand: "Lenovo",
      need: "Office",
      price: 1707,
      energyClass: "C",
      ges: "B",
      batteryMovable: false,
      batteryRecyclability: 60,
      screenSize: 12,
      shutDownAuto: false,
      autonomy: 14,
      description: "Avec le MacBook Pro, l’ordinateur portable atteint des sommets inédits en matière de performances et de portabilité. Quelles que soient les contrées où vous mènera votre imagination, vous parviendrez plus vite que jamais à vos objectifs grâce, entre autres, à des processeurs et à une mémoire hautes performances, à des graphismes avancés et à un système de stockage d’une rapidité fulgurante.",
      image: "http://www.directdial.com/dd2/img/item/300x300-ORIGINAL/2/20HR006KUS.jpg",
      model: "LENOVO X1 CARBON 4G LTE",
      ecologyNotice: "Moyen plus"
    },
    {
      id: 275,
      category: "Computer",
      brand: "Dell",
      need: "Gaming",
      price: 1599,
      energyClass: "F",
      ges: "E",
      batteryMovable: false,
      batteryRecyclability: 52,
      screenSize: 14,
      shutDownAuto: false,
      autonomy: 85,
      description: "Ordinateur portable 15 pouces avec les fonctionnalités essentielles dont vous avez besoin et plus encore, y compris les derniers processeurs Intel®, ainsi que les technologies CinemaStream et CinemaSound.",
      image: "http://www.delixir.com/7543-2313-large/pc-portables-dell-vostro-3568-1w1hp-core-i5-7200u-4-go-ddr4-156-500-go-win10-pro.jpg",
      model: "Dell Vostro 15 3568",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 276,
      category: "Computer",
      brand: "Dell",
      need: "Design",
      price: 1057,
      energyClass: "D",
      ges: "D",
      batteryMovable: true,
      batteryRecyclability: 84,
      screenSize: 15,
      shutDownAuto: true,
      autonomy: 69,
      description: "Ordinateur portable 15 pouces avec les fonctionnalités essentielles dont vous avez besoin et plus encore, y compris les derniers processeurs Intel®, ainsi que les technologies CinemaStream et CinemaSound.",
      image: "https://i.ebayimg.com/images/g/FH4AAOSwo9ZatZnL/s-l300.png",
      model: "Dell Inspiron 15-3567",
      ecologyNotice: "Moyen moins"
    },
    {
      id: 277,
      category: "Computer",
      brand: "Dell",
      need: "Video",
      price: 1151,
      energyClass: "F",
      ges: "D",
      batteryMovable: false,
      batteryRecyclability: 17,
      screenSize: 17,
      shutDownAuto: true,
      autonomy: 49,
      description: "Ordinateur portable 15 pouces avec les fonctionnalités essentielles dont vous avez besoin et plus encore, y compris les derniers processeurs Intel®, ainsi que les technologies CinemaStream et CinemaSound.",
      image: "https://images-eu.ssl-images-amazon.com/images/I/41dNijhJCHL._SY300_QL70_.jpg",
      model: "Dell G3 3579",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 278,
      category: "Computer",
      brand: "HP",
      need: "Design",
      price: 1500,
      energyClass: "F",
      ges: "D",
      batteryMovable: true,
      batteryRecyclability: 62,
      screenSize: 15,
      shutDownAuto: false,
      autonomy: 6,
      description: "Quand la concurrence est impitoyable, seuls les héros qui sauront saisir l’occasion prouveront leur grandeur. Équipé d’un matériel puissant et d’un design agressif, l’ordinateur portable OMEN offre une performance mobile de qualité, vous permettant de relever n’importe quel défi de n’importe quel jeu, n’importe où.",
      image: "https://i.lbdn.com/IMGPRMAX/LEN01613_2.jpg",
      model: "HP 15-db0026nf",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 279,
      category: "Computer",
      brand: "HP",
      need: "Design",
      price: 1751,
      energyClass: "F",
      ges: "A",
      batteryMovable: false,
      batteryRecyclability: 75,
      screenSize: 13,
      shutDownAuto: false,
      autonomy: 30,
      description: "Quand la concurrence est impitoyable, seuls les héros qui sauront saisir l’occasion prouveront leur grandeur. Équipé d’un matériel puissant et d’un design agressif, l’ordinateur portable OMEN offre une performance mobile de qualité, vous permettant de relever n’importe quel défi de n’importe quel jeu, n’importe où.",
      image: "https://store.hp.com/FranceStore/Html/Merch/Images/c05988767_500x367.jpg",
      model: "HP Pavilion 15-cs0016nf",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 280,
      category: "Computer",
      brand: "HP",
      need: "Video",
      price: 1724,
      energyClass: "F",
      ges: "C",
      batteryMovable: false,
      batteryRecyclability: 49,
      screenSize: 11,
      shutDownAuto: true,
      autonomy: 27,
      description: "Quand la concurrence est impitoyable, seuls les héros qui sauront saisir l’occasion prouveront leur grandeur. Équipé d’un matériel puissant et d’un design agressif, l’ordinateur portable OMEN offre une performance mobile de qualité, vous permettant de relever n’importe quel défi de n’importe quel jeu, n’importe où.",
      image: "http://www.agmi.fr/img/PORTABLE/21011732_3d3d0d329f928076a9f074a51250a911_normal.png",
      model: "HP 17-ca0008nf",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 281,
      category: "Computer",
      brand: "Apple",
      need: "Office",
      price: 985,
      energyClass: "B",
      ges: "B",
      batteryMovable: true,
      batteryRecyclability: 69,
      screenSize: 13,
      shutDownAuto: true,
      autonomy: 74,
      description: "Si le MacBook Air est aussi réactif, c’est qu’il est entièrement conçu autour du stockage flash. Non seulement cette particularité le rend plus léger et plus maniable que les portables classiques, mais elle permet un accès plus rapide aux données. Ce stockage flash PCIe est jusqu’à 9 fois plus rapide qu’un disque dur de portable classique à 5 400 tr/min3. À peine ouvert, votre MacBook Air est opérationnel. Même après un mois d’inactivité, son écran s’anime instantanément.",
      image: "https://i.ebayimg.com/images/g/mZEAAOSwQcJaMbbu/s-l300.png",
      model: "MacBook Air",
      ecologyNotice: "Bien"
    },
    {
      id: 282,
      category: "Computer",
      brand: "Apple",
      need: "Gaming",
      price: 504,
      energyClass: "D",
      ges: "D",
      batteryMovable: true,
      batteryRecyclability: 86,
      screenSize: 11,
      shutDownAuto: false,
      autonomy: 42,
      description: "Il n'a pas été simple d'obtenir autant de fonctionnalités Premium dans l'ordinateur le plus fin1 au monde, mais nous l'avons fait. ",
      image: "https://cdn.shopify.com/s/files/1/0050/1589/6153/products/Macbook_Pro_Website_Pic_300x300.png?v=1541996148",
      model: "MacBook Pro",
      ecologyNotice: "Moyen moins"
    },
    {
      id: 283,
      category: "Computer",
      brand: "Acer",
      need: "Design",
      price: 759,
      energyClass: "B",
      ges: "A",
      batteryMovable: true,
      batteryRecyclability: 45,
      screenSize: 16,
      shutDownAuto: true,
      autonomy: 14,
      description: "Il n'a pas été simple d'obtenir autant de fonctionnalités Premium dans l'ordinateur le plus fin1 au monde, mais nous l'avons fait. ",
      image: "https://dyw7ncnq1en5l.cloudfront.net/optim/produits/38/40705/acer-swift-5_bb0f8a285be83968__300_300.jpg",
      model: "Acer Aspire A515-52-32TD",
      ecologyNotice: "Bien"
    },
    {
      id: 284,
      category: "Computer",
      brand: "Acer",
      need: "Design",
      price: 405,
      energyClass: "A",
      ges: "A",
      batteryMovable: true,
      batteryRecyclability: 3,
      screenSize: 17,
      shutDownAuto: false,
      autonomy: 53,
      description: "Il n'a pas été simple d'obtenir autant de fonctionnalités Premium dans l'ordinateur le plus fin1 au monde, mais nous l'avons fait. ",
      image: "https://dyw7ncnq1en5l.cloudfront.net/optim/produits/150/42279/vivobook-s15-2018_2ea7c4306a27fc94__300_300.png",
      model: "Acer Swift SF315-52G-54WS",
      ecologyNotice: "Tres bien"
    },
    {
      id: 285,
      category: "Computer",
      brand: "Acer",
      need: "Design",
      price: 467,
      energyClass: "C",
      ges: "F",
      batteryMovable: false,
      batteryRecyclability: 8,
      screenSize: 13,
      shutDownAuto: true,
      autonomy: 96,
      description: "Il n'a pas été simple d'obtenir autant de fonctionnalités Premium dans l'ordinateur le plus fin1 au monde, mais nous l'avons fait. ",
      image: "https://i.lbdn.com/IMGPRMAX/THO00811.jpg",
      model: "Acer Aspire A315-32-P1ZH",
      ecologyNotice: "Moyen plus"
    },
    {
      id: 286,
      category: "Computer",
      brand: "Samsung",
      need: "Gaming",
      price: 1289,
      energyClass: "C",
      ges: "A",
      batteryMovable: false,
      batteryRecyclability: 87,
      screenSize: 13,
      shutDownAuto: false,
      autonomy: 96,
      description: "Le Samsung Galaxy S8 est le nouveau fleuron de la marque coréenne. Equipé d'un écran Super Amoled de 5,8 pouces sans bords, ce modèle se distingue par son format allongé au ratio 18,5:9. Puissant, il embarque le processeur Exynos 8895 avec 4 Go de mémoire vive.",
      image: "https://www.compsource.com/mscs_images/new_pics/300/w0s99utaba_195.png",
      model: "Samsung Chromebook Plus 513C24I",
      ecologyNotice: "Moyen plus"
    },
    {
      id: 287,
      category: "Phone",
      brand: "Apple",
      need: "Office",
      price: 687,
      energyClass: "F",
      ges: "A",
      batteryMovable: false,
      batteryRecyclability: 9,
      screenSize: 6,
      shutDownAuto: true,
      autonomy: 7,
      description: "Avec le MacBook Pro, l’ordinateur portable atteint des sommets inédits en matière de performances et de portabilité. Quelles que soient les contrées où vous mènera votre imagination, vous parviendrez plus vite que jamais à vos objectifs grâce, entre autres, à des processeurs et à une mémoire hautes performances, à des graphismes avancés et à un système de stockage d’une rapidité fulgurante.",
      image: "https://www.smartphonerecycle.fr/smartphone/apple/iphone-xs-max/apple-iphone-xs-max-64go-medium.png",
      model: "Apple iPhone XS",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 288,
      category: "Phone",
      brand: "Apple",
      need: "Design",
      price: 1122,
      energyClass: "D",
      ges: "D",
      batteryMovable: false,
      batteryRecyclability: 32,
      screenSize: 6,
      shutDownAuto: false,
      autonomy: 20,
      description: "Avec le MacBook Pro, l’ordinateur portable atteint des sommets inédits en matière de performances et de portabilité. Quelles que soient les contrées où vous mènera votre imagination, vous parviendrez plus vite que jamais à vos objectifs grâce, entre autres, à des processeurs et à une mémoire hautes performances, à des graphismes avancés et à un système de stockage d’une rapidité fulgurante.",
      image: "http://ynzal.com/wp-content/uploads/2015/02/ME297LLA1.png",
      model: "Apple iPhone 5s",
      ecologyNotice: "Moyen moins"
    },
    {
      id: 289,
      category: "Phone",
      brand: "Apple",
      need: "Design",
      price: 622,
      energyClass: "F",
      ges: "B",
      batteryMovable: true,
      batteryRecyclability: 38,
      screenSize: 5,
      shutDownAuto: false,
      autonomy: 37,
      description: "Avec le MacBook Pro, l’ordinateur portable atteint des sommets inédits en matière de performances et de portabilité. Quelles que soient les contrées où vous mènera votre imagination, vous parviendrez plus vite que jamais à vos objectifs grâce, entre autres, à des processeurs et à une mémoire hautes performances, à des graphismes avancés et à un système de stockage d’une rapidité fulgurante.",
      image: "https://www.smartphonerecycle.fr/smartphone/apple/iphone-8-plus/apple-iphone-8-256-go-medium.png",
      model: "Apple iPhone 8",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 290,
      category: "Phone",
      brand: "Apple",
      need: "Video",
      price: 552,
      energyClass: "A",
      ges: "A",
      batteryMovable: false,
      batteryRecyclability: 74,
      screenSize: 4,
      shutDownAuto: false,
      autonomy: 45,
      description: "Avec le MacBook Pro, l’ordinateur portable atteint des sommets inédits en matière de performances et de portabilité. Quelles que soient les contrées où vous mènera votre imagination, vous parviendrez plus vite que jamais à vos objectifs grâce, entre autres, à des processeurs et à une mémoire hautes performances, à des graphismes avancés et à un système de stockage d’une rapidité fulgurante.",
      image: "https://d1kvfoyrif6wzg.cloudfront.net/assets/images/63/main/none_16d2b620f0f7ef5896ed3514d7085163_16d2b62.PNG",
      model: "Apple iPhone 7",
      ecologyNotice: "Tres bien"
    },
    {
      id: 291,
      category: "Phone",
      brand: "Asus",
      need: "Video",
      price: 448,
      energyClass: "B",
      ges: "F",
      batteryMovable: false,
      batteryRecyclability: 88,
      screenSize: 5,
      shutDownAuto: false,
      autonomy: 80,
      description: "Jamais aucun autre ordinateur portable n'avait offert autant de puissance que le ZenBook Pro 15. Ses performances sont plus rapides, son design plus élégant et son nouveau ScreenPad™ décuple votre créativité ! Avec le ZenBook Pro vous faites un saut dans le temps : le futur est ici et maintenant ! ",
      image: "https://mon-set-up-gaming.fr/wp-content/uploads/2018/11/asus-rog-phone-300x300.png",
      model: "Asus ROG PHONE",
      ecologyNotice: "Bien"
    },
    {
      id: 292,
      category: "Phone",
      brand: "Asus",
      need: "Design",
      price: 764,
      energyClass: "F",
      ges: "C",
      batteryMovable: true,
      batteryRecyclability: 82,
      screenSize: 5,
      shutDownAuto: true,
      autonomy: 88,
      description: "Jamais aucun autre ordinateur portable n'avait offert autant de puissance que le ZenBook Pro 15. Ses performances sont plus rapides, son design plus élégant et son nouveau ScreenPad™ décuple votre créativité ! Avec le ZenBook Pro vous faites un saut dans le temps : le futur est ici et maintenant ! ",
      image: "https://mon-set-up-gaming.fr/wp-content/uploads/2018/11/asus-rog-phone-300x300.png",
      model: "ASUS ZenFone Max",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 293,
      category: "Phone",
      brand: "Samsung",
      need: "Design",
      price: 877,
      energyClass: "E",
      ges: "A",
      batteryMovable: true,
      batteryRecyclability: 76,
      screenSize: 5,
      shutDownAuto: true,
      autonomy: 53,
      description: "Le Samsung Galaxy S8 est le nouveau fleuron de la marque coréenne. Equipé d'un écran Super Amoled de 5,8 pouces sans bords, ce modèle se distingue par son format allongé au ratio 18,5:9. Puissant, il embarque le processeur Exynos 8895 avec 4 Go de mémoire vive.",
      image: "https://i.ebayimg.com/images/g/B9wAAOSwze5bqz5x/s-l300.jpg",
      model: "Samsung S9",
      ecologyNotice: "Pas bien"
    },
    {
      id: 294,
      category: "Phone",
      brand: "Samsung",
      need: "Office",
      price: 1033,
      energyClass: "F",
      ges: "F",
      batteryMovable: false,
      batteryRecyclability: 13,
      screenSize: 4,
      shutDownAuto: false,
      autonomy: 67,
      description: "Le Samsung Galaxy S8 est le nouveau fleuron de la marque coréenne. Equipé d'un écran Super Amoled de 5,8 pouces sans bords, ce modèle se distingue par son format allongé au ratio 18,5:9. Puissant, il embarque le processeur Exynos 8895 avec 4 Go de mémoire vive..",
      image: "http://i.priice.com/300/2-samsung-galaxy-a6plus-2018.jpg",
      model: "Samsung A6",
      ecologyNotice: "Pas bien du tout"
    },
    {
      id: 295,
      category: "Phone",
      brand: "Samsung",
      need: "Design",
      price: 496,
      energyClass: "A",
      ges: "B",
      batteryMovable: false,
      batteryRecyclability: 28,
      screenSize: 4,
      shutDownAuto: true,
      autonomy: 32,
      description: "Le Samsung Galaxy S8 est le nouveau fleuron de la marque coréenne. Equipé d'un écran Super Amoled de 5,8 pouces sans bords, ce modèle se distingue par son format allongé au ratio 18,5:9. Puissant, il embarque le processeur Exynos 8895 avec 4 Go de mémoire vive.",
      image: "http://i.priice.com/300/samsung-galaxy-j6.jpg",
      model: "Samsung J6",
      ecologyNotice: "Tres bien"
    },
    {
      id: 296,
      category: "Phone",
      brand: "Samsung",
      need: "Video",
      price: 650,
      energyClass: "E",
      ges: "C",
      batteryMovable: true,
      batteryRecyclability: 24,
      screenSize: 5,
      shutDownAuto: false,
      autonomy: 81,
      description: "Le Samsung Galaxy S8 est le nouveau fleuron de la marque coréenne. Equipé d'un écran Super Amoled de 5,8 pouces sans bords, ce modèle se distingue par son format allongé au ratio 18,5:9. Puissant, il embarque le processeur Exynos 8895 avec 4 Go de mémoire vive.",
      image: "http://i.priice.com/300/samsung-galaxy-a3-2016.png",
      model: "Samsung J3",
      ecologyNotice: "Pas bien"
    },
    {
      id: 297,
      category: "Tv",
      brand: "Samsung",
      need: "Office",
      price: 453,
      energyClass: "C",
      ges: "D",
      batteryMovable: false,
      batteryRecyclability: 1,
      screenSize: 40,
      shutDownAuto: true,
      autonomy: 59,
      description: "La TV Led Samsung Galaxy est le nouveau fleuron de la marque coréenne. Equipée d'un écran 4K de 40 pouces, ce modèle se distingue par son format allongé au ratio 18,5:9. Puissant, il embarque Android TV",
      image: "https://yo-location.com/wp-content/uploads/2015/11/television.jpg",
      model: "TV Led Samsung 50NU7025",
      ecologyNotice: "Moyen plus"
    },
    {
      id: 298,
      category: "Tablet",
      brand: "Apple",
      need: "Design",
      price: 410,
      energyClass: "E",
      ges: "D",
      batteryMovable: false,
      batteryRecyclability: 18,
      screenSize: 11,
      shutDownAuto: false,
      autonomy: 70,
      description: "Avec le MacBook Pro, l’ordinateur portable atteint des sommets inédits en matière de performances et de portabilité. Quelles que soient les contrées où vous mènera votre imagination, vous parviendrez plus vite que jamais à vos objectifs grâce, entre autres, à des processeurs et à une mémoire hautes performances, à des graphismes avancés et à un système de stockage d’une rapidité fulgurante.",
      image: "https://png.pngtree.com/element_origin_min_pic/16/11/16/14582bf78fbc6a9.jpg",
      model: "iPad 2",
      ecologyNotice: "Pas bien"
    }
  ];

export default Database;